package parkingGarage;

public enum MsgTypes {
	UNDEFINED, NEWGARAGE, OPERATORLOGIN, OPERATORLOGOUT, SUCCESS, GETREPORT, NEWTICKET, LOOKUPUNPAIDTICKET, TICKETPAID,
	LOOKUPPAIDTICKET, RECEIVED, GARAGELOGIN
}
