package parkingGarage;

public enum MsgTypes {
	UNDEFINED, NEWGARAGE, OPERATORLOGIN, OPERATORLOGOUT, OPERATORSUCCESS, OPERATORFAILURE, SUCCESS, GETREPORT,
	NEWTICKET, LOOKUPUNPAIDTICKET, TICKETPAID, LOOKUPPAIDTICKET, RECEIVED, GARAGELOGIN, SEARCHTICKET, SETRATE
}
